name: Publish Packages

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      - name: Setup Node.js 12.x
        uses: actions/setup-node@v1
        with:
          version: '12.x'
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn test

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      - name: Setup Node.js 12.x
        uses: actions/setup-node@v1
        with:
          version: '12.x'
      - name: Install dependencies
        run: yarn
      - name: Create release pull-request
        uses: changesets/action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Publish
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      - name: Setup Node.js 12.x
        uses: actions/setup-node@v1
        with:
          version: '12.x'
          registry-url: https://npm.pkg.github.com/
          scope: "@pindoio"
      - name: Install dependencies
        run: yarn
      - name: Publish on github registry
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
