name: Publish

on:
  pull_request:
    types: [closed]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: https://npm.pkg.github.com/
          scope: "@pindoio"
      - name: Installing dependencies
        run: yarn
      - name: Publishing package to github registry
        run: yarn auto-publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
