name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    container: 'node:12-alpine'
    steps:
      - uses: actions/checkout@v1
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: yarn workspace blocjs build
      - run: npx semantic-release -e semantic-release-monorepo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
